version: "3.4"

services:
  database:
    container_name: database-server-dab-p1-85ab93e3-e6ae-4080-b28e-66f9fae6514a
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env