version: "3.4"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - exodus-api
      - exodus-ui
    ports:
      - 5000:5000

  exodus-api:
    container_name: exodus-api
    build: exodus-api
    image: exodus-api
    restart: "no"
    volumes:
      - ./exodus-api/:/exodus
    expose:
      - 4000
    depends_on:
      - database
      - flyway

  exodus-ui:
    container_name: exodus-ui
    build: exodus-ui
    image: exodus-ui
    restart: "no"
    volumes:
      - ./exodus-ui/:/exodus
    expose:
      - 3000
    depends_on:
      - exodus-api
    
  database:
    container_name: exodus-sql-server
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env